---
- name: Deploy Node.js application on My-Practical-Task-instance
  hosts: web
  become: yes
  tasks:
    # Install prerequisites
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install Node.js and npm
      apt:
        name: 
          - nodejs
          - npm
        state: present

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    # Deploy application
    - name: Create application directory
      file:
        path: /var/www/nodeapp
        state: directory
        mode: '0755'

    - name: Copy application files
      copy:
        src: ./app/
        dest: /var/www/nodeapp/

    - name: Install Node.js dependencies
      command:
        cmd: npm install --development
        chdir: /var/www/nodeapp

    - name: Start Node.js application
      command:
        cmd: node app.js
        chdir: /var/www/nodeapp
      async: 30
      poll: 0

    # Configure Nginx
    - name: Configure Nginx for Node.js application
      copy:
        dest: /etc/nginx/sites-available/nodeapp
        content: |
          server {
              listen 80;
              server_name _;

              location / {
                  proxy_pass http://localhost:3000;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host $host;
                  proxy_cache_bypass $http_upgrade;
              }
          }

    - name: Enable Nginx configuration
      file:
        src: /etc/nginx/sites-available/nodeapp
        dest: /etc/nginx/sites-enabled/nodeapp
        state: link

    - name: Remove default Nginx configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
----------------------------------------------------------------------------

Commands

terraform apply

ansible-playbook -i inventory.ini playbook.yml

